alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
name: spaces-tracker-api
region: sfo
services:
  - environment_slug: php
    github:
      branch: main
      deploy_on_push: true
      repo: amycodes/do-tracker-api
    http_port: 8080
    instance_count: 2
    instance_size_slug: professional-xs
    name: do-tracker-api
    routes:
      - path: /
    run_command: heroku-php-apache2
    source_dir: /
